states:
  - q0
  - q1
  - qf
initial_state: q0
final_states:
  - qf
tape_alphabet:
  - a
  - b
  - _
input_alphabet:
  - a
  - b
transitions:
  q0:
    a: [q1, a, R]
    b: [q1, b, R]
  q1:
    _: [qf, _, R]
inputs:
  - aaabbb
  - aabb
  - bbaa
